name: on-pr
on: 
  pull_request:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: dummyorg42/which/main
        run: echo "dummyorg42/which/main"
      - name: Failing step
        id: demo
        run: exit 1
      - name: The demo step has failed
        if: ${{ failure() && steps.demo.conclusion == 'failure' }}
        run: echo "Failed"
      
  
